"""Party A -> party B transfer evidence (spec Section 5, FR11/FR12).

Runs scripts/transfer_demo.py's whole local email round trip (protect, MIME
email, SMTP to a 127.0.0.1 receiver, Maildir, download, verify) into a
temporary folder with a throwaway key pair, so it never touches keys/ or
evidence/. About one second on the real sample covers.
"""

from __future__ import annotations

import email
import email.policy
import hashlib
import importlib.util
import mailbox
import os
import shutil
import smtplib
import sys
from pathlib import Path

import pytest

from stego_core import pipeline
from stego_core.verdict import Verdict

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "transfer_demo.py"


@pytest.fixture(scope="module")
def transfer_demo():
    spec = importlib.util.spec_from_file_location("transfer_demo", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module  # dataclasses look their module up here
    spec.loader.exec_module(module)
    yield module
    sys.modules.pop(spec.name, None)


def _populate(out: Path) -> None:
    """Stand-ins for committed evidence from an earlier run, plus a file the script does not own."""
    (out / "party-a" / "outbox").mkdir(parents=True)
    (out / "party-a" / "outbox" / "old.stego.png").write_bytes(b"committed stego")
    (out / "party-b").mkdir()
    (out / "party-b" / "old-download.wav").write_bytes(b"committed download")
    (out / "transfer-report.json").write_text('{"all_passed": true}\n', encoding="utf-8")
    (out / "transfer-log.txt").write_text("committed log\n", encoding="utf-8")
    (out / "notes.md").write_text("not generated by the script\n", encoding="utf-8")


def _snapshot(folder: Path) -> dict[str, bytes | None]:
    """Every path under `folder` with its bytes (None for a folder)."""
    return {
        path.relative_to(folder).as_posix(): path.read_bytes() if path.is_file() else None
        for path in sorted(folder.rglob("*"))
    }


def _partials(folder: Path) -> list[str]:
    return sorted(path.name for path in folder.iterdir() if path.name.endswith(".partial"))


@pytest.fixture(scope="module")
def run(transfer_demo, tmp_path_factory):
    base = tmp_path_factory.mktemp("transfer")
    keys = base / "keys"
    _populate(base / "out")  # a re-run over earlier output, like evidence/transfer/
    result = transfer_demo.run_transfer(
        base / "out",
        private_key=keys / "private" / "transfer.pem",
        public_key=keys / "public" / "transfer.pub.pem",
        echo=False,
    )
    return result, keys / "public" / "transfer.pub.pem"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def test_every_check_passes(run):
    result, _ = run
    failed = [item for item in result.report["checks"] if not item["passed"]]
    assert result.all_passed, failed
    assert result.report["all_passed"] is True
    assert (result.out / "transfer-report.json").is_file()
    assert (result.out / "transfer-log.txt").is_file()


def test_email_carries_base64_attachments(run):
    result, _ = run
    raw = (result.out / "party-a" / "sent.eml").read_bytes()
    message = email.message_from_bytes(raw, policy=email.policy.default)
    attachments = {part.get_filename(): part for part in message.iter_attachments()}
    assert set(attachments) == {"transfer-image.stego.png", "transfer-audio.stego.wav"}
    assert attachments["transfer-image.stego.png"].get_content_type() == "image/png"
    assert attachments["transfer-audio.stego.wav"].get_content_type() == "audio/wav"
    assert all(part["Content-Transfer-Encoding"] == "base64" for part in attachments.values())
    assert b"acw1-demo-passphrase-2026" not in raw  # shared out of band only


def test_sha256_matches_on_both_sides(run):
    result, _ = run
    out = result.out
    for name in ("transfer-image.stego.png", "transfer-audio.stego.wav"):
        sent = out / "party-a" / "outbox" / name
        received = out / "party-b" / "downloads" / name
        assert _sha256(received) == _sha256(sent)
        assert received.read_bytes() == sent.read_bytes()
    for record in result.report["party_b"]["files"]:
        assert record["sha256"] == record["sha256_party_a"] == record["sha256_in_email"]
        assert record["sha256_match"] is True and record["bytes_identical"] is True


def test_received_files_verify_authentic_with_public_key(run):
    """Re-verify the downloaded files here rather than trusting the report."""
    result, public_key = run
    public_pem = public_key.read_bytes()
    message = (ROOT / "samples" / "payloads" / "custom.txt").read_bytes()
    for kind, name in (("image", "transfer-image.stego.png"), ("audio", "transfer-audio.stego.wav")):
        outcome = pipeline.verify(
            pipeline.VerifyOptions(
                stego_bytes=(result.out / "party-b" / "downloads" / name).read_bytes(),
                cover_kind=kind,
                public_key_pem=public_pem,
                n_lsb=2,
                media_id=f"P-transfer-{kind}",
                passphrase="acw1-demo-passphrase-2026",
            )
        )
        assert outcome.verdict == Verdict.AUTHENTIC, outcome.reasons
        assert outcome.signature_valid is True
        assert outcome.media_hash_embedded == outcome.media_hash_recomputed
        assert outcome.message_decrypted is True
    extracted = result.out / "party-b" / "extracted"
    assert (extracted / "transfer-image.message.txt").read_bytes() == message
    assert (extracted / "transfer-audio.message.txt").read_bytes() == message


def test_high_bit_flip_in_transit_is_tampered(run):
    result, public_key = run
    tampered = result.out / "party-b" / "tampered" / "transfer-image.high-bit-flipped.png"
    outcome = pipeline.verify(
        pipeline.VerifyOptions(
            stego_bytes=tampered.read_bytes(),
            cover_kind="image",
            public_key_pem=public_key.read_bytes(),
            n_lsb=2,
            media_id="P-transfer-image",
            passphrase="acw1-demo-passphrase-2026",
        )
    )
    assert outcome.verdict == Verdict.TAMPERED
    assert outcome.signature_valid is True
    assert outcome.media_hash_embedded != outcome.media_hash_recomputed
    controls = {(c["control"], c["kind"]): c for c in result.report["negative_controls"]}
    for kind in ("image", "audio"):
        flip = controls[("high_bit_flip_in_transit", kind)]
        assert flip["verdict"] == "Tampered" and flip["sha256_matches_party_a"] is False
        wrong = controls[("wrong_passphrase", kind)]
        assert wrong["verdict"] != "Authentic" and wrong["message_decrypted"] is False


def test_no_private_key_material_in_output(run, transfer_demo, tmp_path):
    result, _ = run
    for path in result.out.rglob("*"):
        if path.is_file():
            assert b"PRIVATE KEY" not in path.read_bytes(), path
    leaky = tmp_path / "leaky"
    leaky.mkdir()
    (leaky / "oops.txt").write_bytes(b"-----BEGIN PRIVATE KEY-----\nabc\n-----END PRIVATE KEY-----\n")
    assert transfer_demo.private_key_leaks(leaky, b"irrelevant") == ["oops.txt"]


def test_smtp_receiver_unstuffs_dots_and_refuses_unknown_mailboxes(transfer_demo, tmp_path):
    raw = (
        b"From: a@acw1.local\r\nTo: party-b@acw1.local\r\nSubject: dots\r\n\r\n"
        b".leading dot survives\r\n..two dots survive\r\nplain line\r\n"
    )
    maildir = tmp_path / "Maildir"
    with transfer_demo.LocalSMTPReceiver(maildir) as receiver:
        transfer_demo.send_via_smtp(receiver.host, receiver.port, raw)
        with pytest.raises(smtplib.SMTPRecipientsRefused):
            transfer_demo.send_via_smtp(receiver.host, receiver.port, raw, recipient="nobody@acw1.local")
    inbox = mailbox.Maildir(maildir, factory=None)
    stored = [inbox.get_bytes(key) for key in inbox.iterkeys()]
    assert len(stored) == 1
    assert stored[0].endswith(b"\n\n.leading dot survives\n..two dots survive\nplain line\n")
    assert any("2 dot-stuffed line(s) restored" in line for line in receiver.transcript)


def test_existing_public_key_without_private_half_is_refused(transfer_demo, tmp_path):
    """Never silently replace a committed public key (the team-key trap)."""
    public = tmp_path / "public.pem"
    public.write_bytes(b"committed public key")
    with pytest.raises(SystemExit):
        transfer_demo.load_or_create_keys(tmp_path / "missing.pem", public)
    assert public.read_bytes() == b"committed public key"


def test_rerun_replaces_generated_files_and_keeps_others(run):
    result, _ = run
    out = result.out
    assert result.all_passed
    assert not (out / "party-a" / "outbox" / "old.stego.png").exists()
    assert not (out / "party-b" / "old-download.wav").exists()
    assert (out / "transfer-log.txt").read_text(encoding="utf-8") != "committed log\n"
    assert (out / "notes.md").read_text(encoding="utf-8") == "not generated by the script\n"
    assert _partials(out.parent) == []  # the build folder next to --out is gone


def test_missing_private_key_leaves_existing_output_untouched(transfer_demo, tmp_path):
    """A clone with the committed public key but not the private half must
    refuse before it touches the committed evidence, not after deleting it."""
    out = tmp_path / "evidence" / "transfer"
    _populate(out)
    before = _snapshot(out)
    public = tmp_path / "keys" / "public" / "transfer.pub.pem"
    public.parent.mkdir(parents=True)
    public.write_bytes(b"committed public key")
    private = tmp_path / "keys" / "private" / "transfer.pem"
    with pytest.raises(SystemExit, match="other half"):
        transfer_demo.run_transfer(out, private_key=private, public_key=public, echo=False)
    assert _snapshot(out) == before
    assert _partials(out.parent) == []
    assert public.read_bytes() == b"committed public key" and not private.exists()


@pytest.mark.parametrize("missing", ["image_cover", "audio_cover", "message_path"])
def test_missing_input_leaves_output_and_keys_untouched(transfer_demo, tmp_path, missing):
    out = tmp_path / "out"
    _populate(out)
    before = _snapshot(out)
    keys = tmp_path / "keys"
    with pytest.raises(SystemExit, match="cannot read"):
        transfer_demo.run_transfer(
            out,
            private_key=keys / "private.pem",
            public_key=keys / "public.pem",
            echo=False,
            **{missing: tmp_path / "no-such-file"},
        )
    assert _snapshot(out) == before
    assert not keys.exists()  # inputs are checked before a key pair is generated


def test_failing_run_leaves_output_untouched(transfer_demo, tmp_path, monkeypatch):
    """A run whose checks fail must not replace passing evidence with failing evidence."""
    out = tmp_path / "out"
    _populate(out)
    before = _snapshot(out)
    # The wrong-passphrase control now uses the right passphrase, so it verifies
    # as Authentic and its "is not Authentic" check fails.
    monkeypatch.setattr(transfer_demo, "WRONG_PASSPHRASE", transfer_demo.PASSPHRASE)
    result = transfer_demo.run_transfer(
        out, private_key=tmp_path / "k" / "private.pem", public_key=tmp_path / "k" / "public.pem", echo=False
    )
    try:
        assert result.all_passed is False
        assert _snapshot(out) == before
        assert _partials(tmp_path) == []
        assert result.out.resolve() != out.resolve()
        report = (result.out / "transfer-report.json").read_text(encoding="utf-8")
        assert '"all_passed": false' in report
    finally:
        shutil.rmtree(result.out, ignore_errors=True)


def test_crash_mid_run_leaves_output_untouched(transfer_demo, tmp_path, monkeypatch):
    out = tmp_path / "out"
    _populate(out)
    before = _snapshot(out)

    def broken(*args, **kwargs):
        raise RuntimeError("simulated crash while composing the email")

    monkeypatch.setattr(transfer_demo, "compose_email", broken)
    with pytest.raises(RuntimeError, match="simulated crash"):
        transfer_demo.run_transfer(
            out,
            private_key=tmp_path / "k" / "private.pem",
            public_key=tmp_path / "k" / "public.pem",
            echo=False,
        )
    assert _snapshot(out) == before
    assert _partials(tmp_path) == []


def test_publish_rolls_back_if_a_rename_fails(transfer_demo, tmp_path, monkeypatch):
    """If swapping in fails part-way, the old entries are all put back."""
    out = tmp_path / "out"
    _populate(out)
    before = _snapshot(out)
    work = tmp_path / ".out.x.partial"
    for name in ("party-a", "party-b"):
        (work / name).mkdir(parents=True)
        (work / name / "new.txt").write_text("new", encoding="utf-8")
    for name in ("transfer-report.json", "transfer-log.txt"):
        (work / name).write_text("new", encoding="utf-8")
    real_replace = os.replace

    def flaky_replace(src, dst):
        if Path(src) == work / "transfer-report.json":
            raise PermissionError("file in use")
        return real_replace(src, dst)

    monkeypatch.setattr(transfer_demo.os, "replace", flaky_replace)
    with pytest.raises(PermissionError):
        transfer_demo._publish(work, out)
    monkeypatch.undo()
    assert _snapshot(out) == before
    assert (work / "party-a" / "new.txt").is_file()  # the new build is back in work, not half in out
